// SPORTS
export const GET_SPORTS_START = 'GET_SPORTS_START';
export const GET_SPORTS_FAIL = 'GET_SPORTS_FAIL';
export const GET_SPORTS_SUCCESS = 'GET_SPORTS_SUCCESS';

// EVENTS
export const GET_LAST_EVENTS_START = 'GET_LAST_EVENTS_START';
export const GET_LAST_EVENTS_FAIL = 'GET_LAST_EVENTS_FAIL';
export const GET_LAST_EVENTS_SUCCESS = 'GET_LAST_EVENTS_SUCCESS';

// LEAGUES
export const GET_LEAGUES_START = 'GET_LEAGUES_START';
export const GET_LEAGUES_FAIL = 'GET_LEAGUES_FAIL';
export const GET_LEAGUES_SUCCESS = 'GET_LEAGUES_SUCCESS';

// TEAMS
export const GET_TEAMS_START = 'GET_TEAMS_START';
export const GET_TEAMS_FAIL = 'GET_TEAMS_FAIL';
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
